# Generated by Django 4.2.3 on 2023-08-27 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_patente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patente',
            old_name='numero_motor',
            new_name='motor',
        ),
    ]
