# Generated by Django 4.2.3 on 2023-09-02 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0004_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reparar', models.CharField(max_length=50)),
                ('ingreso', models.DateField()),
                ('entregado', models.BooleanField()),
            ],
        ),
    ]
